apiVersion: apps/v1
kind: Deployment
metadata:
  name: v4.31
spec:
  selector:
    matchLabels:
      app: v-fly
  replicas: 1
  template:
    metadata:
      labels:
        app: v-fly
    spec:
      # volumes:
      # - name: install
      #   configMap:
      #     name: install.sh  
      # - name: config
      #   configMap:
      #     name: v-config
      imagePullSecrets:
      - name: ghcr-regcred
      containers:
        - name: core
          image: ghcr.io/flouse/v
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 32m
              memory: 64Mi
            limits:
              cpu: 128m
              memory: 256Mi
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: v-fly
  labels:
    app: v-fly
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8080
  selector:
    app: v-fly
  type: ClusterIP
  sessionAffinity: ClientIP